import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'

// Admin client using service role — can create auth users
function getAdminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )
}

function getSupabase(cookieStore: Awaited<ReturnType<typeof cookies>>) {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => cookieStore.getAll(),
        setAll: (c) => c.forEach(({ name, value, options }) => cookieStore.set(name, value, options)),
      },
    }
  )
}

export async function POST(request: NextRequest) {
  try {
    const cookieStore = await cookies()
    const supabase = getSupabase(cookieStore)

    // Verify caller is authenticated
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const adminClient = getAdminClient()

    // Use service role to fetch caller profile — bypasses RLS so this always works
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: callerProfile, error: profileFetchError } = await (adminClient as any)
      .from('profiles')
      .select('role, agency_id')
      .eq('id', user.id)
      .single()

    if (profileFetchError || !callerProfile) {
      console.error('Failed to fetch caller profile:', profileFetchError)
      return NextResponse.json({ error: 'Profile not found' }, { status: 403 })
    }

    const caller = callerProfile as { role: string; agency_id: string | null }
    if (caller.role !== 'admin' && caller.role !== 'super_admin') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }
    const callerAgencyId = caller.agency_id

    const body = await request.json()
    const { full_name, email, password, phone, role, upline_id } = body

    if (!full_name || !email || !password || !role) {
      return NextResponse.json(
        { error: 'full_name, email, password, and role are required' },
        { status: 400 }
      )
    }

    // Step 1: Create auth user with service role
    const { data: newAuthUser, error: createError } = await adminClient.auth.admin.createUser({
      email,
      password,
      email_confirm: true, // Skip email verification
    })

    if (createError || !newAuthUser.user) {
      return NextResponse.json(
        { error: createError?.message || 'Failed to create auth user' },
        { status: 500 }
      )
    }

    const newUserId = newAuthUser.user.id

    // Step 2: Insert profile (agent_code auto-generated by DB trigger)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: newProfile, error: profileError } = await (adminClient as any)
      .from('profiles')
      .insert({
        id: newUserId,
        full_name,
        email,
        phone: phone || null,
        role,
        upline_id: upline_id || null,
        is_active: true,
        must_change_password: true,
        agency_id: callerAgencyId || null,
      })
      .select()
      .single()

    if (profileError) {
      // Rollback: delete the auth user we just created
      await adminClient.auth.admin.deleteUser(newUserId)
      return NextResponse.json(
        { error: 'Failed to create profile: ' + profileError.message },
        { status: 500 }
      )
    }

    return NextResponse.json({ data: newProfile }, { status: 201 })
  } catch (err) {
    console.error('POST /api/agents/invite error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
